name: turtlebot3_ci

on:
  push:
    branches: [ Turtlebot3_practice ]

  #workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup ROS
        uses: ros-tooling/setup-ros@0.1.1
        with:
          required-ros-distributions: melodic

      - run: "git clone --recursive -b Turtlebot3_practice https://github.com/uhobeike/studying_ros-navigation.git"
      - run: "catkin build"
